language: bash
script: echo hello
branches:
  except:
    - master-build-passed
notifications:
  webhooks:
    urls:
      - https://fl-travis-listener.herokuapp.com/notifications?token=10FxKriDwam-PksnISTV9Q
    on_success: always
    on_failure: always
    on_start: always
